spring:
  datasource:
    driver-class-name: org.postgresql.Driver
graphql:
  packages:
    - com.github.goregius
rl-tracker:
  endpoint:
    base-url: https://rocketleague.tracker.network
  page:
    ranked-rating-leaderboards:
      ranks-per-page: 100
---
spring:
  profiles: development
  flyway:
    url: jdbc:postgresql://localhost:5432/rank_inflation
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/rank_inflation
    username: postgres
    password: postgres
---
spring:
  profiles: production
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  datasource:
    username: ${SPRING_DATASOURCE_URL}
    url: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}